BEGIN TRANSACTION;
DROP TABLE IF EXISTS `articles`;
CREATE TABLE IF NOT EXISTS `articles` (
	`id`	INT NOT NULL UNIQUE,
	`name`	CHAR NOT NULL,
	`prix`	INTEGER NOT NULL,
	`description`	TEXT NOT NULL,
	`category`	CHAR NOT NULL,
	`imgsrc`  CHAR NOT NULL,
	PRIMARY KEY(`id`)
);
INSERT INTO `articles` VALUES (1,'Air Wave Gold',2000,'The Air Wave Gold was a racing broom, apparently manufactured in the 1990s. In 1996, the Seeker Weekly magazine compared the Air Wave Gold to the Turbo XXX to see which one was better.','broomstick','assets/imgs/nimbus2000.jpg');
INSERT INTO `articles` VALUES (2,'Australian Flyabout 50',1000,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (3,'Bluebottle',500,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (4,'Cleansweep One',4500,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (5,'Comet 290',300,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (6,'Firebolt',6790,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (7,'Firebolt Supreme',7483,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (8,'Moontrimmer',546,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (9,'Nimbus 2000',3940,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (10,'Nimbus 2001',7583,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','broomstick','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (11,'The Elder Wand',3820,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (12,'Blackthorne wand',1453,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (13,'Ash wand',2049,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (14,'Holy Wand',5784,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (15,'Ashtorn wand',3789,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (16,'Cedar wand',2563,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (17,'Mahogany wand',9583,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (18,'Yew wand',3628,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (19,'Poplar wand',8574,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (20,'Oak wand',4575,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','wand','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (21,'Laugh-inducing Potion',8573,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (22,'Manegro Potion',3562,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (23,'Murtlap Essence',7402,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (24,'Polyjuice Potion',9274,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (25,'Potion No. 86',9474,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (26,'Skele-Gro',7398,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (27,'Strength Potion',8494,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (28,'Truth Serum',3739,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (29,'Wolfsbane Potion',284,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
INSERT INTO `articles` VALUES (30,'Babbling Beverage',7309,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu aliquet est. Sed quam lorem, mollis non vulputate et, cursus eget lacus. Praesent dapibus eros eu tincidunt porta. Nam hendrerit consectetur erat sit amet consectetur.','potion','assets/imgs/Balai-volant-de-sorciere.jpg');
COMMIT;
